# Generated by Django 4.1.1 on 2022-09-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
