# Generated by Django 4.1.1 on 2022-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
