# Generated by Django 4.1.1 on 2022-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0005_alter_postlike_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
