# Generated by Django 4.1.1 on 2022-09-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0007_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewprofile',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='View Profile Date'),
        ),
    ]
