# Generated by Django 4.1.1 on 2022-09-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0009_like_remove_postlike_post_remove_postlike_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='like',
            name='LinkedIn_li_content_400590_idx',
        ),
    ]
