# Generated by Django 4.1.1 on 2022-09-22 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0010_remove_like_linkedin_li_content_400590_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='name',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
