# Generated by Django 4.1.1 on 2022-09-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0011_remove_like_name_like_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Message Date')),
                ('text', models.TextField(max_length=1000)),
                ('primary_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_user_chat', to=settings.AUTH_USER_MODEL)),
                ('secondary_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_user_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(related_name='users_chat', through='LinkedIn.Chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
