# Generated by Django 4.1.1 on 2022-09-22 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0012_chat_alter_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='primary_user',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='secondary_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
