# Generated by Django 4.1.1 on 2022-09-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0013_remove_chat_primary_user_remove_chat_secondary_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Message Date'),
        ),
    ]
