# Generated by Django 4.1.1 on 2022-09-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedIn', '0015_alter_comment_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
